name: swan_sync
description: "SWAN Sync - Seamless data synchronization with FCM and Hive."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  device_info_plus: ^11.5.0
  firebase_messaging: ^15.1.4
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # HTTP and networking
  http: ^1.2.2
  # Storage
  shared_preferences: ^2.3.3
  # Utils
  uuid: ^4.5.1
  # JSON serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
