name: swan_sync_demo
description: "SWAN Sync - Seamless data synchronization with FCM and Hive."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  device_info_plus: ^11.5.0
  firebase_messaging: ^15.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.5

  swan_sync:
    git:
      url: https://github.com/jfletcher20/swan_sync.git
      ref: main
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
